Repository numaproj/numalogic, pull requests merged in 2023-05, with the labels that each got.

#163 Benchmark v0.4
  Makefile
  benchmarks/README.md
  benchmarks/__init__.py
  benchmarks/kpi/README.md
  benchmarks/kpi/__init__.py
  benchmarks/kpi/benchmark.ipynb
  benchmarks/kpi/datamodule.py
  benchmarks/kpi/results/kpi_idx_14/conv/hyperparams.json
  benchmarks/kpi/results/kpi_idx_14/conv/pr_curve_test.png
  benchmarks/kpi/results/kpi_idx_14/conv/roc_test.png
  benchmarks/kpi/results/kpi_idx_14/conv/roc_val.png
  benchmarks/kpi/results/kpi_idx_14/conv/test.png
  benchmarks/kpi/results/kpi_idx_14/conv/train.png
  benchmarks/kpi/results/kpi_idx_14/conv/val.png
  benchmarks/kpi/results/kpi_idx_14/lstm/hyperparams.json
  benchmarks/kpi/results/kpi_idx_14/lstm/pr_curve_test.png
  benchmarks/kpi/results/kpi_idx_14/lstm/roc_test.png
  benchmarks/kpi/results/kpi_idx_14/lstm/roc_val.png
  benchmarks/kpi/results/kpi_idx_14/lstm/test.png
  benchmarks/kpi/results/kpi_idx_14/lstm/train.png
  benchmarks/kpi/results/kpi_idx_14/lstm/val.png
  benchmarks/kpi/results/kpi_idx_14/transformer/hyperparams.json
  benchmarks/kpi/results/kpi_idx_14/transformer/pr_curve_test.png
  benchmarks/kpi/results/kpi_idx_14/transformer/roc_test.png
  benchmarks/kpi/results/kpi_idx_14/transformer/roc_val.png
  benchmarks/kpi/results/kpi_idx_14/transformer/test.png
  benchmarks/kpi/results/kpi_idx_14/transformer/train.png
  benchmarks/kpi/results/kpi_idx_14/transformer/val.png
  benchmarks/kpi/results/kpi_idx_14/vanilla/hyperparams.json
  benchmarks/kpi/results/kpi_idx_14/vanilla/pr_curve_test.png
  benchmarks/kpi/results/kpi_idx_14/vanilla/roc_test.png
  benchmarks/kpi/results/kpi_idx_14/vanilla/roc_val.png
  benchmarks/kpi/results/kpi_idx_14/vanilla/test.png
  benchmarks/kpi/results/kpi_idx_14/vanilla/train.png
  benchmarks/kpi/results/kpi_idx_14/vanilla/val.png
  benchmarks/plots.py
  numalogic/config/_config.py
  numalogic/tools/data.py
  pyproject.toml
  tests/tools/test_data.py
Labels: area/examples

#164 chore!: drop support for python 3.8
  .github/workflows/ci.yml
  pyproject.toml
Labels: chore

#170 add: redis registry
  numalogic/config/__init__.py
  numalogic/config/_config.py
  numalogic/config/factory.py
  numalogic/registry/__init__.py
  numalogic/registry/_serialize.py
  numalogic/registry/artifact.py
  numalogic/registry/mlflow_registry.py
  numalogic/registry/redis_registry.py
  numalogic/tools/exceptions.py
  numalogic/tools/types.py
  poetry.lock
  pyproject.toml
  tests/registry/test_redis_registry.py
  tests/registry/test_serialize.py
  tests/resources/config.yaml
  tests/test_config.py
Labels: enhancement, area/registry

#174 chore: allow actions for release branches
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yaml
  .github/workflows/lint.yml
Labels: chore

#179 fix: add redis caching
  numalogic/registry/artifact.py
  numalogic/registry/localcache.py
  numalogic/registry/redis_registry.py
  tests/registry/test_cache.py
  tests/registry/test_mlflow_registry.py
  tests/registry/test_redis_registry.py
Labels: enhancement, area/registry, DO NOT MERGE

#190 chore!: Auto detect instance type while mlflow model save
  docs/ml-flow.md
  numalogic/registry/mlflow_registry.py
  numalogic/tools/types.py
  poetry.lock
  pyproject.toml
  tests/registry/test_mlflow_registry.py
Labels: area/registry

#193 chore: fix version
  pyproject.toml
Labels: release

#199 fix: Sparse AE for vanilla and conv
  benchmarks/kpi/README.md
  benchmarks/kpi/benchmark.ipynb
  benchmarks/kpi/results/kpi_idx_14/sparseconv/hyperparams.json
  benchmarks/kpi/results/kpi_idx_14/sparseconv/pr_curve_test.png
  benchmarks/kpi/results/kpi_idx_14/sparseconv/roc_test.png
  benchmarks/kpi/results/kpi_idx_14/sparseconv/roc_val.png
  benchmarks/kpi/results/kpi_idx_14/sparseconv/test.png
  benchmarks/kpi/results/kpi_idx_14/sparseconv/train.png
  benchmarks/kpi/results/kpi_idx_14/sparseconv/val.png
  benchmarks/kpi/results/kpi_idx_14/sparsevanilla/hyperparams.json
  benchmarks/kpi/results/kpi_idx_14/sparsevanilla/pr_curve_test.png
  benchmarks/kpi/results/kpi_idx_14/sparsevanilla/roc_test.png
  benchmarks/kpi/results/kpi_idx_14/sparsevanilla/roc_val.png
  benchmarks/kpi/results/kpi_idx_14/sparsevanilla/test.png
  benchmarks/kpi/results/kpi_idx_14/sparsevanilla/train.png
  benchmarks/kpi/results/kpi_idx_14/sparsevanilla/val.png
  numalogic/models/autoencoder/trainer.py
  numalogic/models/autoencoder/variants/conv.py
  numalogic/models/autoencoder/variants/vanilla.py
  numalogic/tools/data.py
  tests/models/autoencoder/variants/test_conv.py
  tests/tools/test_data.py
Labels: area/ml

#200 docs: update docstrings; add pycodestyle check
  README.md
  benchmarks/kpi/datamodule.py
  benchmarks/plots.py
  examples/numalogic-simple-pipeline/src/udf/inference.py
  examples/numalogic-simple-pipeline/src/udf/postprocess.py
  examples/numalogic-simple-pipeline/src/udf/preprocess.py
  examples/numalogic-simple-pipeline/src/udf/threshold.py
  examples/numalogic-simple-pipeline/src/udf/train.py
  examples/numalogic-simple-pipeline/src/udf_factory.py
  examples/numalogic-simple-pipeline/src/utils.py
  numalogic/config/_config.py
  numalogic/config/factory.py
  numalogic/models/autoencoder/base.py
  numalogic/models/autoencoder/trainer.py
  numalogic/models/autoencoder/variants/conv.py
  numalogic/models/autoencoder/variants/lstm.py
  numalogic/models/autoencoder/variants/transformer.py
  numalogic/models/autoencoder/variants/vanilla.py
  numalogic/models/forecast/variants/naive.py
  numalogic/models/threshold/_static.py
  numalogic/models/threshold/_std.py
  numalogic/postprocess.py
  numalogic/preprocess/transformer.py
  numalogic/registry/artifact.py
  numalogic/registry/localcache.py
  numalogic/registry/mlflow_registry.py
  numalogic/registry/redis_registry.py
  numalogic/synthetic/anomalies.py
  numalogic/synthetic/sparsity.py
  numalogic/synthetic/timeseries.py
  numalogic/tools/__init__.py
  numalogic/tools/callbacks.py
  numalogic/tools/data.py
  numalogic/tools/exceptions.py
  numalogic/tools/types.py
  pyproject.toml
Labels: documentation
