Repository numaproj/numalogic, pull requests merged in 2023-06, with the labels that each got.

#201 chore!: refactor preproc and postproc into transforms module
  Makefile
  docs/post-processing.md
  docs/pre-processing.md
  docs/quick-start.md
  examples/numalogic-simple-pipeline/src/udf/postprocess.py
  examples/numalogic-simple-pipeline/src/udf/preprocess.py
  examples/numalogic-simple-pipeline/src/udf/train.py
  numalogic/__init__.py
  numalogic/base.py
  numalogic/config/factory.py
  numalogic/models/autoencoder/base.py
  numalogic/models/forecast/variants/naive.py
  numalogic/models/threshold/_static.py
  numalogic/models/threshold/_std.py
  numalogic/registry/redis_registry.py
  numalogic/tools/__init__.py
  numalogic/tools/types.py
  numalogic/transforms/__init__.py
  numalogic/transforms/_movavg.py
  numalogic/transforms/_postprocess.py
  numalogic/transforms/_scaler.py
  numalogic/transforms/_stateless.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/config/test_config.py
  tests/transforms/__init__.py
  tests/transforms/test_postprocess.py
  tests/transforms/test_transforms.py
Labels: chore

#202 examples: update with new numalogic and pynumaflow
  examples/numalogic-simple-pipeline/numa-pl.yaml
  examples/numalogic-simple-pipeline/requirements.txt
  examples/numalogic-simple-pipeline/src/factory.py
  examples/numalogic-simple-pipeline/src/udf/__init__.py
  examples/numalogic-simple-pipeline/src/udf/inference.py
  examples/numalogic-simple-pipeline/src/udf/postprocess.py
  examples/numalogic-simple-pipeline/src/udf/preprocess.py
  examples/numalogic-simple-pipeline/src/udf/threshold.py
  examples/numalogic-simple-pipeline/src/udf/train.py
  examples/numalogic-simple-pipeline/src/udf_factory.py
  examples/numalogic-simple-pipeline/src/utils.py
  examples/numalogic-simple-pipeline/starter.py
  numalogic/numaflow/__init__.py
  numalogic/numaflow/_base.py
  poetry.lock
  pyproject.toml
  tests/test_numaflow.py
Labels: area/examples

#210 release: v0.4.0post1
  numalogic/registry/redis_registry.py
  poetry.lock
  pyproject.toml
Labels: release

#206 feat!: introduce numalogic blocks
  numalogic/base.py
  numalogic/blocks/__init__.py
  numalogic/blocks/_base.py
  numalogic/blocks/_nn.py
  numalogic/blocks/_transform.py
  numalogic/blocks/pipeline.py
  numalogic/registry/artifact.py
  numalogic/tools/types.py
  poetry.lock
  pyproject.toml
  tests/blocks/__init__.py
  tests/blocks/test_blocks.py
  tests/blocks/test_pipeline.py
Labels: enhancement

#211 Upgraded python support for 3.11
  .github/workflows/ci.yml
  pyproject.toml
Labels: good first issue

#216 examples: pipeline using block
  examples/block_pipeline/.dockerignore
  examples/block_pipeline/Dockerfile
  examples/block_pipeline/numa-pl.yaml
  examples/block_pipeline/requirements.txt
  examples/block_pipeline/resources/train_data.csv
  examples/block_pipeline/server.py
  examples/block_pipeline/src/__init__.py
  examples/block_pipeline/src/inference.py
  examples/block_pipeline/src/train.py
  examples/block_pipeline/src/utils.py
  examples/multi_udf/.dockerignore
  examples/multi_udf/Dockerfile
  examples/multi_udf/README.md
  examples/multi_udf/entry.sh
  examples/multi_udf/numa-pl.yaml
  examples/multi_udf/requirements.txt
  examples/multi_udf/src/__init__.py
  examples/multi_udf/src/factory.py
  examples/multi_udf/src/resources/train_data.csv
  examples/multi_udf/src/udf/__init__.py
  examples/multi_udf/src/udf/inference.py
  examples/multi_udf/src/udf/postprocess.py
  examples/multi_udf/src/udf/preprocess.py
  examples/multi_udf/src/udf/threshold.py
  examples/multi_udf/src/udf/train.py
  examples/multi_udf/src/utils.py
  examples/multi_udf/starter.py
Labels: area/examples

#218 release: v0.4.1
  .github/workflows/ci.yml
  CHANGELOG.md
  examples/block_pipeline/.dockerignore
  examples/block_pipeline/Dockerfile
  examples/block_pipeline/numa-pl.yaml
  examples/block_pipeline/requirements.txt
  examples/block_pipeline/resources/train_data.csv
  examples/block_pipeline/server.py
  examples/block_pipeline/src/__init__.py
  examples/block_pipeline/src/inference.py
  examples/block_pipeline/src/train.py
  examples/block_pipeline/src/utils.py
  examples/multi_udf/.dockerignore
  examples/multi_udf/Dockerfile
  examples/multi_udf/README.md
  examples/multi_udf/entry.sh
  examples/multi_udf/numa-pl.yaml
  examples/multi_udf/requirements.txt
  examples/multi_udf/src/__init__.py
  examples/multi_udf/src/factory.py
  examples/multi_udf/src/resources/train_data.csv
  examples/multi_udf/src/udf/__init__.py
  examples/multi_udf/src/udf/inference.py
  examples/multi_udf/src/udf/postprocess.py
  examples/multi_udf/src/udf/preprocess.py
  examples/multi_udf/src/udf/threshold.py
  examples/multi_udf/src/udf/train.py
  examples/multi_udf/src/utils.py
  examples/multi_udf/starter.py
  numalogic/base.py
  numalogic/blocks/__init__.py
  numalogic/blocks/_base.py
  numalogic/blocks/_nn.py
  numalogic/blocks/_transform.py
  numalogic/blocks/pipeline.py
  numalogic/registry/artifact.py
  numalogic/tools/types.py
  poetry.lock
  pyproject.toml
  tests/blocks/__init__.py
  tests/blocks/test_blocks.py
  tests/blocks/test_pipeline.py
Labels: release

#221 fix: update production key to latest key
  .github/workflows/lint.yml
  benchmarks/plots.py
  examples/multi_udf/src/factory.py
  examples/multi_udf/src/udf/train.py
  numalogic/blocks/pipeline.py
  numalogic/config/factory.py
  numalogic/models/autoencoder/trainer.py
  numalogic/models/autoencoder/variants/conv.py
  numalogic/registry/artifact.py
  numalogic/registry/mlflow_registry.py
  numalogic/registry/redis_registry.py
  numalogic/synthetic/anomalies.py
  numalogic/synthetic/timeseries.py
  numalogic/tools/types.py
  poetry.lock
  pyproject.toml
Labels: bug, area/registry

#222 fix: dataset slicing
  numalogic/tools/data.py
  tests/tools/test_data.py
Labels: bug

#220 feat!: add dynamodb registry
  numalogic/registry/__init__.py
  numalogic/registry/dynamodb_registry.py
  numalogic/tools/exceptions.py
  poetry.lock
  pyproject.toml
  tests/registry/test_dynamodb_registry.py
Labels: enhancement, area/registry
