Repository numaproj/numalogic, pull requests merged in 2023-03, with the labels that each got.

#139 feat: tanh preprocessing
  docs/pre-processing.md
  numalogic/config/factory.py
  numalogic/preprocess/__init__.py
  numalogic/preprocess/transformer.py
  pyproject.toml
  tests/preprocess/test_transformer.py
Labels: area/ml

#141 feat: Sigmoid threshold
  docs/quick-start.md
  docs/threshold.md
  numalogic/models/threshold/__init__.py
  numalogic/models/threshold/_static.py
  numalogic/models/threshold/_std.py
  numalogic/registry/mlflow_registry.py
  poetry.lock
  pyproject.toml
  tests/models/test_threshold.py
  tests/registry/test_mlflow_registry.py
Labels: area/ml

#146 add: anomaly sign and return labels for anomalies generated
  examples/quick-start.ipynb
  numalogic/synthetic/anomalies.py
  poetry.lock
  pyproject.toml
  tests/synthetic/test_anomalies.py
Labels: enhancement, area/synthetic

#153 fix: Tanhscaler nan output for constant feature
  numalogic/preprocess/transformer.py
  pyproject.toml
  tests/preprocess/test_transformer.py
Labels: bug

#155 fix: validation loss not being logged
  numalogic/models/autoencoder/trainer.py
  numalogic/tools/callbacks.py
  numalogic/tools/data.py
  tests/models/autoencoder/test_trainer.py
  tests/models/autoencoder/variants/test_conv.py
  tests/tools/test_data.py
Labels: bug
